[package]
name = "rust-yew-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
gloo = { version = "0.8.1" }
serde = { version = "1.0.171" }
serde_json = { version = "1.0.102" }
