[serve]
port = 25566

[watch]
watch = ["src", "index.html", "tailwind.config.js", "postcss.config.js", "Cargo.toml"]

[[hooks]]
stage = "post_build"
command = "cmd"
command_arguments = ["/C npx tailwindcss -i ./src/tailwind.css -o ./dist/.stage/index.css"]
