[[hooks]]
stage = "post_build"
command = "cmd"
command_arguments = ["/C npx tailwindcss -i ./src/tailwind.css -o ./dist/.stage/index.css"]

[serve]
address = "127.0.0.1"
port = 25566
open = true

[watch]
watch = ["src", "index.html", "tailwind.config.js", "postcss.config.js"]